### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by ozyyshr** [Junpliu/ConDigSum#1]
Hi, thanks for the wonderful work.
When will the source code be released?

**Comment by Junpliu** [comment]
Hi, sorry for the late update because of some busy things. We will release the code and trained models in a week or so as soon as possible.

**Comment by skpig** [comment]
@Junpliu Thanks for the great work. I'm trying to reproduce your paper, it will be appreciated if you may release the source code. BTW, if possible, please report the ROUGE (F-value) under comprehensive planning and focus planning settings.

**Comment by krystalan** [comment]
Hi, thanks for your remarkable work! Could u pls release the generated results on the test sets of SAMSum and MediaSum datasets? and When will the code be released? It could be helpful for others to follow this wonderful work!
